/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh1: THREE.Mesh;
  };
  materials: {};
};

export default function XModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/X.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh1.geometry}
        material={nodes.Mesh1.material}
      />
    </group>
  );
}

// Fix for preload with correct arguments
useGLTF.preload(
  "/models/X.glb",
  false, // useDraco
  false, // useMeshopt
  undefined // extendLoader (optional)
);
