/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh1: THREE.Mesh;
  };
  materials: object;
};

export default function XModel({
  color,
  scale,
  ...props
}: JSX.IntrinsicElements["group"] & {
  color?: string;
  scale?: number;
}) {
  const { nodes } = useGLTF("/models/X.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh1.geometry}
        material={nodes.Mesh1.material}
      />
      <meshBasicMaterial color={color} />
    </group>
  );
}

// Fix for preload with correct arguments
useGLTF.preload(
  "/models/X.glb",
  false, // useDraco
  false, // useMeshopt
  undefined // extendLoader (optional)
);
